// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewynVOendizcQtgrp1x8kT5BTjEEXRpU',
    appId: '1:682509714388:web:ffeaed366f8947a34c4c41',
    messagingSenderId: '682509714388',
    projectId: 'asistencia-uni-2025',
    authDomain: 'asistencia-uni-2025.firebaseapp.com',
    storageBucket: 'asistencia-uni-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDustHdL79u1VkUKNqmBK-NGFITweOeEVw',
    appId: '1:682509714388:android:74e98ad5dbc6e75d4c4c41',
    messagingSenderId: '682509714388',
    projectId: 'asistencia-uni-2025',
    storageBucket: 'asistencia-uni-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpnBu_Hp3vwGEEK56SfajuXFW5NaGn6o',
    appId: '1:682509714388:ios:48ff601c0a623c614c4c41',
    messagingSenderId: '682509714388',
    projectId: 'asistencia-uni-2025',
    storageBucket: 'asistencia-uni-2025.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaUni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpnBu_Hp3vwGEEK56SfajuXFW5NaGn6o',
    appId: '1:682509714388:ios:48ff601c0a623c614c4c41',
    messagingSenderId: '682509714388',
    projectId: 'asistencia-uni-2025',
    storageBucket: 'asistencia-uni-2025.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaUni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDewynVOendizcQtgrp1x8kT5BTjEEXRpU',
    appId: '1:682509714388:web:e4c7c7c2da5c4e834c4c41',
    messagingSenderId: '682509714388',
    projectId: 'asistencia-uni-2025',
    authDomain: 'asistencia-uni-2025.firebaseapp.com',
    storageBucket: 'asistencia-uni-2025.firebasestorage.app',
  );
}
